import { NextRequest, NextResponse } from 'next/server';
import { spawn, spawnSync } from 'child_process';
import { promises as fs } from 'fs';
import { join } from 'path';
import { z } from 'zod';
import crypto from 'crypto';
import { getEOPDataset } from '@/lib/eopDatasets';
import { requireApiAuth } from '@/lib/apiAuth';

export const dynamic = 'force-dynamic';
const NO_STORE_HEADERS = {
  'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
  Pragma: 'no-cache',
  Expires: '0',
};

const ParamsSchema = z.object({
  windowSize: z.number().positive().default(365),
  turnThreshold: z.number().positive().default(0.05),
  centerWindow: z.number().positive().default(60),
  centerStep: z.number().positive().default(5),
  danceWindow: z.number().positive().default(120),
  conditionalTargetState: z.number().int().min(0).max(3).default(2),
  pathResolution: z.enum(['low', 'medium', 'high']).default('medium'),
});
const SelectSchema = z.enum(['full', 'conditionalLagModel']).default('full');

let pythonCommand: string | null = null;
const activeComputations = new Map<string, Promise<void>>();

function getPythonCommand() {
  if (pythonCommand) {
    return pythonCommand;
  }

  const candidates = [
    process.env.DRIFT_PYTHON,
    process.env.PYTHON,
    process.env.PYTHON3,
    join(process.cwd(), '.venv', 'bin', 'python'),
    join(process.env.HOME || '', '.pyenv', 'versions', '3.12.7', 'bin', 'python'),
    'python3',
    'python',
  ].filter(Boolean) as string[];

  for (const candidate of candidates) {
    const check = spawnSync(candidate, ['-c', 'import numpy, scipy, pandas'], {
      stdio: 'ignore',
    });

    if (check.status === 0) {
      pythonCommand = candidate;
      return pythonCommand;
    }
  }

  throw new Error('No Python interpreter with numpy, scipy, and pandas is available. Set DRIFT_PYTHON to a compatible interpreter.');
}

export async function GET(request: NextRequest) {
  const authResponse = requireApiAuth(request);
  if (authResponse) {
    return authResponse;
  }

  try {
    const searchParams = request.nextUrl.searchParams;
    
    const params = ParamsSchema.parse({
      windowSize: searchParams.get('windowSize') ? parseFloat(searchParams.get('windowSize')!) : 365,
      turnThreshold: searchParams.get('turnThreshold') ? parseFloat(searchParams.get('turnThreshold')!) : 0.05,
      centerWindow: searchParams.get('centerWindow') ? parseFloat(searchParams.get('centerWindow')!) : 60,
      centerStep: searchParams.get('centerStep') ? parseFloat(searchParams.get('centerStep')!) : 5,
      danceWindow: searchParams.get('danceWindow') ? parseFloat(searchParams.get('danceWindow')!) : 120,
      conditionalTargetState: searchParams.get('conditionalTargetState') ? parseInt(searchParams.get('conditionalTargetState')!, 10) : 2,
      pathResolution: searchParams.get('pathResolution') || 'medium',
    });
    const select = SelectSchema.parse(searchParams.get('select') || 'full');

    const dataset = getEOPDataset(searchParams.get('dataset'));
    const dataPath = join(process.cwd(), 'public', 'data', dataset.filename);
    
    const scriptPath = join(process.cwd(), 'scripts', 'compute_rolling_stats.py');

    const [dataStat, scriptStat] = await Promise.all([
      fs.stat(dataPath),
      fs.stat(scriptPath),
    ]);

    // Create parameter-based cache key. Include source/script metadata so model
    // or input changes cannot reuse stale outputs generated by older code,
    // without reading the full input file before every cache lookup.
    const cacheKey = crypto.createHash('md5')
      .update(JSON.stringify(params))
      .update(dataset.id)
      .update(`${dataStat.mtimeMs}:${dataStat.size}`)
      .update(`${scriptStat.mtimeMs}:${scriptStat.size}`)
      .digest('hex');
    
    const cacheDir = join(process.cwd(), 'public', 'data', '.rolling-stats-cache', dataset.id, params.pathResolution);
    const cachePath = join(cacheDir, `${cacheKey}.json`);

    // Ensure cache directory exists
    await fs.mkdir(cacheDir, { recursive: true });

    // Check cache
    let statsData: any = null;
    
    try {
      const stat = await fs.stat(cachePath);
      const ageMinutes = (Date.now() - stat.mtime.getTime()) / 1000 / 60;
      
      if (ageMinutes < 60) {
        const dataStr = await fs.readFile(cachePath, 'utf8');
        statsData = JSON.parse(dataStr);
      }
    } catch (err) {
      // Cache miss
    }

    // If not cached, run computation
    if (!statsData) {
      let activeComputation = activeComputations.get(cachePath);
      if (!activeComputation) {
        activeComputation = runPythonComputation(
          dataPath,
          cachePath,
          params.windowSize,
          params.turnThreshold,
          params.centerWindow,
          params.centerStep,
          params.danceWindow,
          params.conditionalTargetState,
          params.pathResolution
        ).finally(() => {
          activeComputations.delete(cachePath);
        });
        activeComputations.set(cachePath, activeComputation);
      }

      await activeComputation;

      const dataStr = await fs.readFile(cachePath, 'utf8');
      statsData = JSON.parse(dataStr);
    }

    const responseData = select === 'conditionalLagModel'
      ? { conditionalLagModel: statsData?.conditionalLagModel ?? null }
      : statsData;

    return NextResponse.json(responseData, { headers: NO_STORE_HEADERS });
  } catch (error) {
    console.error('Error computing rolling stats:', error);
    return NextResponse.json({ error: 'Failed to compute rolling stats' }, { status: 500, headers: NO_STORE_HEADERS });
  }
}

async function runPythonComputation(
  inputPath: string,
  outputPath: string,
  windowSize: number,
  turnThreshold: number,
  centerWindow: number,
  centerStep: number,
  danceWindow: number,
  conditionalTargetState: number,
  pathResolution: string
) {
  return new Promise<void>((resolve, reject) => {
    const scriptPath = join(process.cwd(), 'scripts', 'compute_rolling_stats.py');
    
    let command: string;
    try {
      command = getPythonCommand();
    } catch (error) {
      reject(error);
      return;
    }

    const python = spawn(command, [
      scriptPath,
      '--input', inputPath,
      '--output', outputPath,
      '--window-size', windowSize.toString(),
      '--turn-threshold', turnThreshold.toString(),
      '--center-window', centerWindow.toString(),
      '--center-step', centerStep.toString(),
      '--dance-window', danceWindow.toString(),
      '--conditional-target-state', conditionalTargetState.toString(),
      '--path-resolution', pathResolution.toString()
    ]);

    let stderr = '';
    python.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    python.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Python script failed with code ${code}: ${stderr}`));
      }
    });
  });
}
